[workspace]
resolver = "3"
members = ["crates/iroh-social-types", "src-tauri"]

[workspace.package]
edition = "2024"
version = "0.1.16"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
iroh-gossip = "0.96"
anyhow = "1"
