[package]
name = "iroh-social-types"
version.workspace = true
edition.workspace = true

[dependencies]
iroh = "0.96"
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
iroh-gossip = { workspace = true }
